This is a tutorial for learning the first steps of working with TensorFlow.

This tutorial is mainly based on these resources:<br>
Books:<br>
Building Machine Learning Projects with TensorFlow > books/TensorFlow

TensorFlow is using data flow graphs. Nodes in the graph represent mathematical operations, while the graph edges represent the multidimensional data arrays (tensors) passed between them.<br>
A tensor is just a typed, multidimensional array, with
additional operations, modeled in the tensor object.<br>

### Tensor rank
Tensor ranks represent the dimensional aspect of a tensor. A rank one tensor is the equivalent of a vector, and a rank one tensor is a matrix. For a rank two tensor you can access any element with the syntax t[i, j]. For a rank three tensor you would need to address an element with t[i, j, k], and so on.

### Tensor shape
It shows the shape of each dimension of our tensor. For example:(2,2) for a 2*2 matrix

### Tensor data types
float(32,64), int(8,16,32,64), string, bool

### Creating new tensors
We can either create our own tensors, or derivate them from the well-known numpy library:

from numpy:<br>
x = tf.constant(np.random.rand(32).astype(np.float32))<br>
self created:<br>
y= tf.constant ([1,2,3])<br>

Another example:<br>
x_data = np.array([[1.,2.,3.],[3.,2.,6.]]) # 2x3 matrix<br>
x = tf.convert_to_tensor(x_data, dtype=tf.float32)<br>

##### Convert to tensor
tf.convert_to_tensor : This function converts Python objects of various types to tensor objects. It accepts tensorobjects, numpy arrays, Python lists, and Python scalars.<br>

### TensorFlow's data flow graph
A data flow graph is, succinctly, a complete TensorFlow computation, represented as a graph where nodes are operations and edges are data flowing between operations.

For example, c = tf.matmul(a, b) creates an operation of MatMul type that takes tensors a and b as input and produces c as output.

#### Useful operation object methods
tf.Operation.type : Returns the type of the operation (for example, MatMul)<br>
tf.Operation.inputs : Returns the list of tensor objects representing the operation's inputs<br>
tf.Graph.get_operations() : Returns the list of operations in the graph<br>
tf.Graph.version : Returns the graph's autonumeric version



In [1]:
import tensorflow as tf

## Better Tutorial
This is a better tutorial from: "Getting Started with TensorFlow"

### Placeholders
A placeholder allows us to create our operations and to build our computation graph, without needing the data.

Placeholders are like variables in programming and later we can send values or other variables to fill them and use them. The reason that we use placeholders is tensorflow needs to know what and which variables it needs to build its computation graph.

Below code is a good and simple example from that book:

In [4]:
a = tf.placeholder("int32")
b = tf.placeholder("int32")

y = tf.multiply(a,b)

sess = tf.Session()

print (sess.run(y , feed_dict={a: 2, b: 5}))

10


In [7]:
x = tf.constant([[1,2,3],[4,5,6]])
y = tf.constant([[5,2],[8,9],[2,1]])

c = tf.matmul(x,y)
sess = tf.Session()
sess.as_default()
print (c)

Tensor("MatMul_4:0", shape=(2, 2), dtype=int32)


### Viewing the values

In [9]:
print (c.eval(session=sess))

[[27 23]
 [72 59]]


#### Variables
For machine learning applications of TensorFlow, the parameters of the model are typically stored in tensors held in variables, and are updated when running the training graph for the model.

In [16]:
b = tf.Variable(tf.zeros([100]))
b

<tf.Variable 'Variable_2:0' shape=(100,) dtype=float32_ref>

### Saving data flow graphs
Data flow graphs are written using Google's protocol buffers.

"tf.Graph.as_graph_def(from_version=None, add_shapes=False)" : returns a serialized GraphDef representation of this graph.

Parameters:
- from_version : If this is set, it returns a GraphDef with nodes that were added from this version
- add_shapes : If true , adds a shape attribute to each node

#### Example graph building
In this example we will build a very simple data flow graph, and observe an overview of the generated protobuffer file:

In [19]:
g = tf.Graph()
with g.as_default():
    import tensorflow as tf
    sess = tf.Session()
    W_m = tf.Variable(tf.zeros([10, 5]))
    x_v = tf.placeholder(tf.float32, [None, 10])
    result = tf.matmul(x_v, W_m)
print (g.as_graph_def())

node {
  name: "zeros"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 10
          }
          dim {
            size: 5
          }
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "Variable"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 10
        }
        dim {
          size: 5
        }
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "Variable/Assign"
  op: "Assign"
  input: "Variable"
  input: "zeros"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }


# Sessions: Running our programs
- The Session object is a representation of the environment in which the computation will run.
- The Session object starts empty, and when the programmer creates the different operations and tensors, they will be added automatically to the Session, which will do no computation until the Run() method is called
- The Run() method takes a set of output names that need to be computed, as well as an optional set of tensors to be fed into the graph in place of certain outputs of nodes
- This simple line is the only one needed to create a Session: "sses = tf.Session()"

------------------

# Basic tensor methods

## Simple matrix operations
TensorFlow supports many of the more common matrix operations, such as transpose, multiplication, getting the determinant, and inverse.

In [2]:
sess = tf.InteractiveSession()
x = tf.constant([[2, 5, 3, -5],[0, 3,-2, 5],[4, 3, 5, 3],[6, 1, 4, 0]])
y = tf.constant([[4, -7, 4, -3, 4],[6, 4,-7, 4, 7],[2, 3, 2, 1, 4],[1, 5,
5, 5, 2]])
floatx = tf.constant([[2., 5., 3., -5.],[0., 3.,-2., 5.],[4., 3., 5.,
3.],[6., 1., 4., 0.]])


In [3]:
tf.transpose(x).eval() # Transpose matrix

array([[ 2,  0,  4,  6],
       [ 5,  3,  3,  1],
       [ 3, -2,  5,  4],
       [-5,  5,  3,  0]], dtype=int32)

In [4]:
tf.matmul(x, y).eval()

array([[ 39, -10, -46,  -8,  45],
       [ 19,  31,   0,  35,  23],
       [ 47,  14,  20,  20,  63],
       [ 38, -26,  25, -10,  47]], dtype=int32)

In [5]:
tf.matrix_determinant(floatx).eval()

818.0

In [6]:
tf.matrix_inverse(floatx).eval()

array([[-0.00855745,  0.10513447, -0.18948655,  0.29584354],
       [ 0.12958434,  0.12224938,  0.01222495, -0.05134475],
       [-0.01955992, -0.18826404,  0.28117359, -0.18092909],
       [-0.08557458,  0.05134474,  0.10513448, -0.0415648 ]], dtype=float32)

In [7]:
tf.matrix_solve(floatx, [[1],[1],[1],[1]]).eval() #Solves systems of linear equations.

array([[ 0.202934  ],
       [ 0.21271393],
       [-0.10757945],
       [ 0.02933985]], dtype=float32)

## Reduction
Reduction is an operation that applies an operation across one of the tensor's dimensions, leaving it with one less dimension.<br>
The supported operations include (with the same parameters) product, minimum, maximum, mean, all, any, and accumulate_n).

In [9]:
x = tf.constant([[1, 2, 3],[3, 2, 1],[-1,-2,-3]])
boolean_tensor = tf.constant([[True, False, True],[False, False,
True],[True, False, False]])

In [10]:
# product of each row
tf.reduce_prod(x, reduction_indices=1).eval()

array([ 6,  6, -6], dtype=int32)

In [11]:
# minimum of each row
tf.reduce_min(x, reduction_indices=1).eval()

array([ 1,  1, -3], dtype=int32)

In [12]:
tf.reduce_max(x, reduction_indices=1).eval()

array([ 3,  3, -1], dtype=int32)

In [13]:
tf.reduce_mean(x, reduction_indices=1).eval()

array([ 2,  2, -2], dtype=int32)

In [14]:
tf.reduce_all(boolean_tensor, reduction_indices=1).eval()

array([False, False, False], dtype=bool)

In [15]:
tf.reduce_any(boolean_tensor, reduction_indices=1).eval()

array([ True,  True,  True], dtype=bool)

## Tensor segmentation
Must be read from the book

In [16]:
seg_ids = tf.constant([0,1,1,2,2]); # Group indexes : 0,1&2,3&4
tens1 = tf.constant([[2, 5, 3, -5],[0, 3,-2, 5],[4, 3, 5, 3],[6, 1,
4, 0],[6, 1, 4, 0]]) # A sample constant matrix

In [17]:
# sums rows based on the segmentation
tf.segment_sum(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 4,  6,  3,  8],
       [12,  2,  8,  0]], dtype=int32)

In [18]:
tf.segment_prod(tens1, seg_ids).eval()

array([[  2,   5,   3,  -5],
       [  0,   9, -10,  15],
       [ 36,   1,  16,   0]], dtype=int32)

In [19]:
tf.segment_min(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 0,  3, -2,  3],
       [ 6,  1,  4,  0]], dtype=int32)

In [20]:
tf.segment_max(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 4,  3,  5,  5],
       [ 6,  1,  4,  0]], dtype=int32)

In [21]:
tf.segment_mean(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 2,  3,  1,  4],
       [ 6,  1,  4,  0]], dtype=int32)

## Sequences
Sequence utilities include methods such as argmin and argmax (showing the minimum and maximum value of a dimension), listdiff (showing the complement of the intersection between lists), where (showing the index of the true values on a tensor), and unique (showing unique values on a list).

In [22]:
x = tf.constant([[2, 5, 3, -5],[0, 3,-2, 5],[4, 3, 5, 3],[6, 1, 4, 0]])
listx = tf.constant([1,2,3,4,5,6,7,8])
listy = tf.constant([4,5,8,9])
boolx = tf.constant([[True,False], [False,True]])

In [23]:
# this returns the arguments(locations) of the minimum values of each row
tf.argmin(x, 1).eval()

array([3, 2, 1, 3])

In [24]:
tf.argmax(x, 1).eval()

array([1, 3, 2, 0])

In [25]:
tf.where(boolx).eval()

array([[0, 0],
       [1, 1]])

In [26]:
tf.unique(listx)[0].eval()

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [27]:
# elements in listx that are not in listy
tf.setdiff1d(listx, listy)[0].eval()

array([1, 2, 3, 6, 7], dtype=int32)

### Tensor shape transformations
These kinds of functions are related to a matrix shape.

In [28]:
x = tf.constant([[2, 5, 3, -5],[0, 3,-2, 5],[4, 3, 5, 3],[6, 1, 4, 0]])

In [29]:
tf.shape(x).eval() # Shape of the tensor

array([4, 4], dtype=int32)

In [31]:
tf.size(x).eval() # total numbers of tensor

16

In [32]:
tf.rank(x).eval()

2

In [33]:
tf.reshape(x, [8, 2]).eval()

array([[ 2,  5],
       [ 3, -5],
       [ 0,  3],
       [-2,  5],
       [ 4,  3],
       [ 5,  3],
       [ 6,  1],
       [ 4,  0]], dtype=int32)

In [34]:
tf.expand_dims(x,1).eval()

array([[[ 2,  5,  3, -5]],

       [[ 0,  3, -2,  5]],

       [[ 4,  3,  5,  3]],

       [[ 6,  1,  4,  0]]], dtype=int32)

## Tensor Slicing and Joining
In order to extract and merge useful information from big datasets, the slicing and joining methods allow you to consolidate the required column information without having to occupy memory space with nonspecific information.

In [35]:
t_matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
t_array = tf.constant([1,2,3,4,9,8,6,5])
t_array2= tf.constant([2,3,4,5,6,7,8,9])

In [36]:
# Slicing a 2*2 matrix from 3*3 matrix
# It slices from the row1 and column1 to row2 and column2
tf.slice(t_matrix, [1, 1], [2,2]).eval()

array([[5, 6],
       [8, 9]], dtype=int32)

In [38]:
# Splits a tensor into sub tensors.
tf.split(axis=0, num_or_size_splits=2, value=t_array)

[<tf.Tensor 'split:0' shape=(4,) dtype=int32>,
 <tf.Tensor 'split:1' shape=(4,) dtype=int32>]

In [40]:
# Constructs a tensor by tiling a given tensor.
tf.tile([1,2],[3]).eval()

array([1, 2, 1, 2, 1, 2], dtype=int32)

In [42]:
# Pads a tensor.
tf.pad(t_matrix, [[0,1],[2,1]]).eval()

array([[0, 0, 1, 2, 3, 0],
       [0, 0, 4, 5, 6, 0],
       [0, 0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [44]:
tf.concat(axis=0, values=[t_array, t_array2]).eval()

array([1, 2, 3, 4, 9, 8, 6, 5, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [45]:
tf.stack([t_array, t_array2]).eval()

array([[1, 2, 3, 4, 9, 8, 6, 5],
       [2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)

In [46]:
# Unpacks the given dimension of a rank-`R` tensor into rank-`(R-1)` tensors.
sess.run(tf.unstack(t_matrix))

[array([1, 2, 3], dtype=int32),
 array([4, 5, 6], dtype=int32),
 array([7, 8, 9], dtype=int32)]

In [48]:
# Reverses specific dimensions of a tensor.
tf.reverse(t_matrix, [False,True]).eval()

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]], dtype=int32)

*********

## Dataflow structure and results visualization - TensorBoard
TensorBoard is a software utility that allows the graphical representation of the data flow graph and a dashboard used for the interpretation of results.

#### Command-line use
tensorboard -h

#### Summaries
To save all the required information, TensorFlow API uses data output objects, called Summaries.<br>
These Summaries write results into TensorFlow event files, which gather all the required data generated during a Session's run.<br>
In the following example, we'll running TensorBoard directly on a generated event log directory:<br>
tensorboard --logdir=. --port=8000

All Summaries in a TensorFlow Session are written by a SummaryWriter object. The main method to call is:<br>
tf.train.SummaryWriter.__init__(logdir, graph_def=None)

This command will create a SummaryWriter and an event file, in the path of the parameter.

The constructor of the the "SummaryWriter" will create a new event file in logdir . This event file will contain "Event" type protocol buffers constructed when you call one of the following functions: add_summary(), add_session_log(), add_event(), or add_graph().

- Operations in TensorFlow don't do anything until you run them, or an operation that depends on their output.
- So, to generate summaries, we need to run all of these summary nodes. Managing them manually would be tedious, so use "tf.merge_all_summaries" to combine them into a single op that generates all the summary data.
- Then, you can just run the merged summary op, which will generate a serialized Summary protobuf object with all of your summary data at a given step.
- Finally, to write this summary data to disk, pass the Summary protobuf to a tf.train.SummaryWriter.
- The "SummaryWriter" takes a "logdir" in its constructor, it's the directory where all of the events will be written out. Also, the "SummaryWriter" can optionally take a "GraphDef" in its constructor. If it receives one, then TensorBoard will visualize your graph as well.

### Common Summary operations
This is a list of the different Summary types, and the parameters employed on its construction:

- tf.scalar_summary (tag, values, collections=None, name=None)
- tf.image_summary (tag, tensor, max_images=3, collections=None, name=None)
- tf.histogram_summary (tag, values, collections=None, name=None)
- tf.merge_summary (inputs, collections=None, name=None)
- tf.merge_all_summaries (key='summaries')


## TensorBoard Example
This example is from:"Getting Started with TensorFlow"

In [8]:
a = tf.constant(10,name="a")
b = tf.constant(90,name="b")
y = tf.Variable(a+b*2, name="y")

model = tf.initialize_all_variables()
# initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
# Instructions for updating: Use `tf.global_variables_initializer` instead.

with tf.Session() as session:
#     merged = tf.merge_all_summaries()
    merged = tf.summary.merge_all() # new method instead of merge_all
#     writer = tf.train.SummaryWriter("/tmp/tensorflowlogs",session.graph)
    writer = tf.summary.FileWriter("/tmp/tensorflowlogs",session.graph) # new method instead of SummaryWritter
    session.run(model)
    print(session.run(y))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
190


### Viewing TensorBoard

terminal:<br>
tensorboard --logdir=/tmp/tsorflowlogs

Browser:<br>
http://ali-Aspire:6006

## Reading Information From Disk
TensorFlow reads a number of the most standard formats, including the well-known CSV, image files (JPG and PNG decoders), and the standard TensorFlow format.

### Reading CSV files
- . First, we must create a filename queue object with the list of files we'll be using
- Then create a "TextLineReader"
- The remaining operation will be to decode the CSV columns, and save it on tensors
- If we want to mix homogeneous data together, the pack method will work
-----------------------------------------

#### CSV Example: The Iris dataset
- The data set consists of 50 samples from each of three species of Iris
- Four features were measured in each sample
- Based on the combination of these four features, Fisher developed a linear discriminant model to distinguish the species from each other

In [ ]:
# Samle code and not working because of file-name
filename_queue = tf.train.string_input_producer(tf.train.match_filenames_once("./*.csv"),
shuffle=True)
reader = tf.TextLineReader(skip_header_lines=1)
key, value = reader.read(filename_queue)
record_defaults = [[0.], [0.], [0.], [0.], [""]]
col1, col2, col3, col4, col5 = tf.decode_csv(value, record_defaults=record_defaults) # Convert CSV records to tensors
features = tf.pack([col1, col2, col3, col4])
# the rest of code

### Reading image data
- TensorFlow allows importing data from image formats
- The accepted image formats will be JPG and PNG, and the internal representation will be uint8 tensors, one rank two tensor for each image channel


#### Loading and processing the images:

In [ ]:
filename_queue = tf.train.string_input_producer(tf.train.match_filenames_once("./blue_jay.jpg"))
reader = tf.WholeFileReader()
key, value = reader.read(filename_queue)
image=tf.image.decode_jpeg(value)
flipImageUpDown=tf.image.encode_jpeg(tf.image.flip_up_down(image))
flipImageLeftRight=tf.image.encode_jpeg(tf.image.flip_left_right(image))
tf.initialize_all_variables().run(session=sess)
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(coord=coord, sess=sess)
example = sess.run(flipImageLeftRight)
print example
file=open ("flippedUpDown.jpg", "wb+")
file.write (flipImageUpDown.eval(session=sess))
file.close()
file=open ("flippedLeftRight.jpg", "wb+")
file.write (flipImageLeftRight.eval(session=sess))
file.close()